# Generated by Django 4.2 on 2023-12-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="QUESTION")),
                ("answer", models.CharField(max_length=3, verbose_name="ANSWER")),
            ],
        ),
    ]
