# Generated by Django 4.2 on 2023-12-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simulation", "0002_sellhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="buy",
            name="is_sell",
            field=models.BooleanField(default=False, verbose_name="Is_sell"),
        ),
    ]
