# Generated by Django 5.0 on 2023-12-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default="noname", max_length=20),
            preserve_default=False,
        ),
    ]
