# Generated by Django 5.0 on 2023-12-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_user_agree_marketing_alter_user_agree_terms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="agree_marketing",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="agree_terms",
            field=models.BooleanField(default=False),
        ),
    ]
