# Generated by Django 5.0 on 2023-12-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_user_created_at_user_last_password_modified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default="someone", max_length=40),
            preserve_default=False,
        ),
    ]
