# Generated by Django 4.2 on 2023-12-20 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="CONTENT")),
                (
                    "create_dt",
                    models.DateTimeField(auto_now_add=True, verbose_name="CREATE DT"),
                ),
                (
                    "update_dt",
                    models.DateTimeField(auto_now=True, verbose_name="UPDATE DT"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="board.post",
                    ),
                ),
            ],
        ),
    ]
